on: 
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '* * * * *'

jobs:
  fetch_menu_job:
    runs-on: ubuntu-latest
    name: Fetches menu and updates gist
    steps:
      - name: Fetch menu step
        id: fetchMenu
        uses: ollitoivanen/OpiskelijalounasWebFetchAction@v0.1
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "Valmis menu"
