on: [push]
  #schedule:
      # * is a special character in YAML so you have to quote this string
    #  - cron:  '* * * * *'

jobs:
  fetch_menu_job:
    runs-on: ubuntu-latest
    name: Fetches menu and updates gist
    steps:
      - name: Fetch menu step
        id: fetchMenu
        uses: ollitoivanen/OpiskelijalounasWebFetchAction@v0.4
      - name: Get the output menu
        run: echo "Valmis menu" #${{ steps.fetchMenu.outputs.menu }}"
