on: [push]
  #schedule:
      # * is a special character in YAML so you have to quote this string
    #  - cron:  '* * * * *'

jobs:
  fetch_menu_job:
    runs-on: ubuntu-latest
    name: Fetches menu and updates gist
    steps:
      - name: Fetch menu step
        id: fetchMenu
        uses: ollitoivanen/OpiskelijalounasWebFetchAction@v0.4
      - name: Get the output menu
        run: |
          curl --request PATCH \
          --url https://api.github.com/gists/ff230a705bc30ecf48ead3042c767143 \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}', "Accept: application/vnd.github.v3+json" \
          --data '{
              "files":"all_restaurants_menu.json",
              "description": "${{ steps.fetchMenu.outputs.menu }}"
            }' \
